// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDs5s75Om6iVo9PgdG5sw3J3xSAXtViHPQ',
    appId: '1:268628109433:web:1ec9bf09074f33a3110ca8',
    messagingSenderId: '268628109433',
    projectId: 'remainder-app-17be9',
    authDomain: 'remainder-app-17be9.firebaseapp.com',
    storageBucket: 'remainder-app-17be9.firebasestorage.app',
    measurementId: 'G-S03LMC5DF4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8pz1Q1Ws0dkda58J23Vjh1CmW450cyS4',
    appId: '1:268628109433:android:316d9b7de1b20195110ca8',
    messagingSenderId: '268628109433',
    projectId: 'remainder-app-17be9',
    storageBucket: 'remainder-app-17be9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJ-a5KmrrYQXkQRLrtsvIZmM9BEJedH6k',
    appId: '1:268628109433:ios:be96297003093250110ca8',
    messagingSenderId: '268628109433',
    projectId: 'remainder-app-17be9',
    storageBucket: 'remainder-app-17be9.firebasestorage.app',
    iosBundleId: 'com.example.remainderApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJ-a5KmrrYQXkQRLrtsvIZmM9BEJedH6k',
    appId: '1:268628109433:ios:be96297003093250110ca8',
    messagingSenderId: '268628109433',
    projectId: 'remainder-app-17be9',
    storageBucket: 'remainder-app-17be9.firebasestorage.app',
    iosBundleId: 'com.example.remainderApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDs5s75Om6iVo9PgdG5sw3J3xSAXtViHPQ',
    appId: '1:268628109433:web:43aab374887ee008110ca8',
    messagingSenderId: '268628109433',
    projectId: 'remainder-app-17be9',
    authDomain: 'remainder-app-17be9.firebaseapp.com',
    storageBucket: 'remainder-app-17be9.firebasestorage.app',
    measurementId: 'G-Z5V9NZQ2N4',
  );
}
